name: Update Docker image

on:
  release:
    types:
      - published

jobs:
  build:
    name: Update Docker image
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Get name of Docker repository name
        id: docker-repo-name
        run: echo NAME=$(echo "${GITHUB_REPOSITORY,,}") >> $GITHUB_OUTPUT

      - name: Build image for tag
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }},ghcr.io/${{ github.repository }}:latest