name: Update Docker image

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  SERVER_NAME: shockedplot7560/pmmpunit
  IMAGE_NAME: tests-runner

jobs:
  build:
    name: Update Docker image
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ubuntu-20.04]
        php: [ "8.1", "8.2", "8.3" ]
        repo: 
          - name: pmmp/PocketMine-MP
            namespace: pmmp
            version: 5.15.0
          - name: Plutonium-Mcpe/PocketMine-MP
            namespace: plutonium
            version: 5.100.1

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e
        with:
          images: ${{ env.REGISTRY }}/${{ env.SERVER_NAME }}/${{ env.IMAGE_NAME }}-php${{ matrix.php }}

      - name: Get name of Docker repository name
        id: docker-repo-name
        run: echo NAME=$(echo "${GITHUB_REPOSITORY,,}") >> $GITHUB_OUTPUT

      - name: Build image for tag
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ env.SERVER_NAME }}/${{ env.IMAGE_NAME }}-php${{ matrix.php }}-${{ matrix.repo.namespace }}:latest
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            PMMP_REPO=${{ matrix.repo.name }}
            PMMP_TAG=${{ matrix.repo.version }}